import { Container } from "@/components/ui/container";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";

export default function PrivacyPolicy() {
    return (
        <main className="min-h-screen bg-black text-white">
            <Navbar />
            <Container className="pt-32 pb-24">
                <div className="max-w-3xl mx-auto space-y-8 text-zinc-300 leading-relaxed">
                    <div>
                        <h1 className="text-4xl font-bold text-white mb-4">Privacy Policy for Framely</h1>
                        <p className="text-zinc-400"><strong>1 Feb 2026:</strong></p>
                        <p className="mt-4">
                            Framely (“we”, “our”, or “the app”) is an AI-powered video generation app. This Privacy Policy explains how we collect, use, and protect your information when you use the Framely mobile application on iOS.
                        </p>
                    </div>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">1. Information We Collect</h2>

                        <h3 className="text-lg font-semibold text-white mt-6">1.1 Account and profile</h3>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Email address</strong> — When you sign up or sign in (e.g. email/password or via “Sign in with Apple”), we store your email to identify your account and communicate with you if needed.</li>
                            <li><strong>Account identifier</strong> — We store a unique user ID and, where applicable, an Apple subscription transaction identifier to manage your subscription and credits.</li>
                        </ul>

                        <h3 className="text-lg font-semibold text-white mt-6">1.2 Usage and subscription data</h3>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Credits and subscription</strong> — We store your credit balance, credit usage, subscription status (e.g. Pro or Ultimate), and related product identifiers to provide in-app purchases and access to features.</li>
                            <li><strong>Usage statistics</strong> — We may store aggregated usage data (e.g. most used AI model) to improve the app and your experience.</li>
                        </ul>

                        <h3 className="text-lg font-semibold text-white mt-6">1.3 Content you create</h3>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Prompts and video metadata</strong> — When you create a video, we store the title, prompt text, selected AI model, and cost in credits. This is necessary to generate, track, and display your videos.</li>
                            <li><strong>Generated videos</strong> — Video files generated by the app are stored so you can view and download them in the app. You can also save videos to your device’s photo library (we do not access your full photo library; we only save the files you choose to save).</li>
                        </ul>

                        <h3 className="text-lg font-semibold text-white mt-6">1.4 Optional: Photos for video generation</h3>
                        <p>If you use “image-to-video” features, you may select one or more photos from your device. Only the images you explicitly choose are sent to our AI providers to generate the video. We do not access or scan your entire photo library.</p>

                        <h3 className="text-lg font-semibold text-white mt-6">1.5 Device and app usage</h3>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Notifications</strong> — If you enable “video ready” notifications, we use your device’s local notification system to notify you when a video is finished. This is handled on your device; we do not store notification content on our servers beyond what is needed to trigger the notification.</li>
                            <li><strong>Receipt and purchase data</strong> — To verify purchases and manage subscriptions and refunds, we may process purchase and receipt information provided by Apple (e.g. transaction identifiers). This is used only for billing and support.</li>
                        </ul>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">2. How We Use Your Information</h2>
                        <p>We use the information above to:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Create and manage your account and profile.</li>
                            <li>Provide subscription and credit-based features and process in-app purchases and refunds.</li>
                            <li>Generate videos using your prompts (and optional images) via third-party AI services.</li>
                            <li>Store and serve your video library and related metadata.</li>
                            <li>Send you local notifications (e.g. when a video is ready) if you have enabled them.</li>
                            <li>Improve the app, fix errors, and comply with legal obligations.</li>
                        </ul>
                        <p>We do not sell your personal information to third parties for advertising or marketing.</p>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">3. Third-Party Services</h2>
                        <p>We use the following types of third-party services:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Authentication and backend</strong> — We use Supabase for account creation, sign-in, profile storage, and video metadata and storage. Supabase’s practices are governed by their privacy policy.</li>
                            <li><strong>Apple</strong> — We use Apple Sign In and Apple’s In-App Purchase and subscription APIs. Apple may collect and process data according to Apple’s Privacy Policy. We receive only the information necessary to identify your account and validate purchases (e.g. transaction IDs).</li>
                            <li><strong>AI and video generation</strong> — Your prompts (and, when you use image-to-video, the images you select) are sent to AI providers we use to generate videos (e.g. providers powering models such as Veo and Grok Imagine). These providers process data under their own privacy and data processing terms.</li>
                            <li><strong>Prompt enhancement (optional)</strong> — We may use a service such as Google’s Gemini to improve or refine your prompt before sending it to the video generation service. The text you enter is processed according to that provider’s policies.</li>
                        </ul>
                        <p>We choose providers with care but are not responsible for their privacy practices. We encourage you to review their policies.</p>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">4. Data Retention</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Account and profile</strong> — We retain your account and profile data for as long as your account is active. If you delete your account, we will delete or anonymize this data in line with our data retention procedures.</li>
                            <li><strong>Videos and prompts</strong> — We retain video metadata and generated videos so you can access them in the app. If you delete your account, we will delete your videos and related data in accordance with our retention policy.</li>
                            <li><strong>Purchase and subscription records</strong> — We may retain minimal purchase-related data (e.g. transaction identifiers) as long as needed for billing, refunds, and legal or tax compliance.</li>
                        </ul>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">5. Your Rights and Choices</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Access and correction</strong> — You can view and update your profile and preferences inside the app where we provide such options.</li>
                            <li><strong>Deletion</strong> — You may request deletion of your account and associated data by contacting us (see “Contact” below). We will process your request in line with applicable law.</li>
                            <li><strong>Notifications</strong> — You can turn off “video ready” notifications at any time in the app settings.</li>
                            <li><strong>Photo access</strong> — You can revoke the app’s access to your photo library in your device’s Settings. The app will then not be able to use your photos for image-to-video until you grant access again.</li>
                        </ul>
                        <p>Depending on where you live, you may have additional rights (e.g. under GDPR or CCPA). Contact us to exercise them.</p>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">6. Security</h2>
                        <p>We use industry-standard measures to protect your data, including secure connections (HTTPS), secure authentication, and access controls. No system is completely secure; we encourage you to use a strong password and keep your device secure.</p>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">7. Children</h2>
                        <p>Framely is not directed at children under 13 (or the applicable age in your country). We do not knowingly collect personal information from children. If you believe we have collected such information, please contact us and we will delete it.</p>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">8. International Data</h2>
                        <p>Your data may be stored and processed in countries where our service providers operate, including outside your country of residence. We ensure appropriate safeguards where required by law.</p>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">9. Changes to This Policy</h2>
                        <p>We may update this Privacy Policy from time to time. We will post the updated policy in the app or on our website and will indicate the “Last updated” date. Continued use of the app after changes constitutes acceptance of the updated policy. If changes are significant, we may notify you in the app or by email where appropriate.</p>
                    </section>

                    <hr className="border-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">10. Contact</h2>
                        <p>If you have questions about this Privacy Policy or your data, or to request access or deletion of your data, please contact us at:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Email:</strong> support@framelyapp.net</li>
                            <li><strong>Help & Support (in-app):</strong> Available in Settings</li>
                        </ul>
                    </section>

                    <hr className="border-white/10" />

                    <p className="text-sm text-zinc-500 italic">Framely is provided by Framely Inc.</p>

                </div>
            </Container>
            <Footer />
        </main>
    );
}
